In [35]:
import pandas as pd
import random

df_train = pd.read_csv("train.csv")

In [11]:
df_train

                            text     label
0               nama kamu siapa?  ask_name
1               siapa nama kamu?  ask_name
2        kamu punya nama ga sih?  ask_name
3          aku panggil kamu apa?  ask_name
4   kamu biasanya dipanggil apa?  ask_name
5                    kamu siapa?  ask_name
6                  siapa namamu?  ask_name
7                     nama kamu?  ask_name
8                          cuaca   weather
9                 cuaca hari ini   weather
10           cuacanya bagaimana?   weather
11         suhu berapa hari ini?   weather
12               perkiraan cuaca   weather
13                kuliah dimana?    campus
14               kamu kuliah ga?    campus
15           apakah kamu kuliah?    campus
16           kamu kuliah dimana?    campus
17          kamu belajar dimana?    campus
18        kamu cari ilmu dimana?    campus
19                 kamu belajar?    campus

In [15]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.naive_bayes import MultinomialNB

X_train, X_test, y_train, y_test = train_test_split(df_train['text'], df_train['label'], random_state = 0)
count_vect = CountVectorizer()
X_train_counts = count_vect.fit_transform(X_train)
tfidf_transformer = TfidfTransformer()
X_train_tfidf = tfidf_transformer.fit_transform(X_train_counts)
clf = MultinomialNB().fit(X_train_tfidf, y_train)

In [30]:
text = "kayanya panas ya, perkiraan cuaca hari ini tau ga?"

label_prediction = clf.predict(count_vect.transform([text]))[0]
proba_prediction = max(clf.predict_proba(count_vect.transform([text]))[0])

print(label_prediction)
print(proba_prediction)

weather
0.8517301688955597

In [31]:
df_response = pd.read_csv("response.csv")

In [32]:
df_response

       label                                           response
0   ask_name     nama aku Bambang, nama panjangnya Bambaaaaaang
1   ask_name                                aku Bambang namanya
2   ask_name                                            Bambang
3   ask_name                                      kamu kepo deh
4   ask_name                        mau tau apa mau tau banget?
5     campus                        tentu kampus ku Uhamka dong
6     campus                      Itu loh di Uhamka, masa gatau
7     campus                               kuliah di Uhamka nih
8     campus  di Uhamka, Universitas Muhammadiyah Prof. DR. ...
9     campus  kampusku ada di Universitas Muhammadiyah Prof....
10   weather  cuaca hari ini hujan, jangan lupa bawa payung yah
11   weather  hari ini nampaknya akan hujan, jangan lupa pak...
12   weather               panas nih, mau ga minum es sama aku?
13   weather  kayanya bakal mendung nih, tapi gatau nanti uj...
14   weather  gerimis nih, jadi teringat kenangan melintasi ...

In [44]:
random.choice(list(df_response.query(f"label == '{label_prediction}'")["response"]))

'hari ini nampaknya akan hujan, jangan lupa pake jaket ya biar kamu ga sakit'